// AUTH
export const SIGNUP_USER_INITIATED = "SIGNUP_USER_INITIATED"
export const SIGNUP_USER_FALIED = "SIGNUP_USER_FALIED"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const LOGIN_USER_INITIATED = "LOGIN_USER_INITIATED"
export const LOGIN_USER_FALIED = "LOGIN_USER_FALIED"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGOUT_USER_INITIATED = "LOGOUT_USER_INITIATED"
export const LOGOUT_USER_FALIED = "LOGOUT_USER_FALIED"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"

// UPLOAD FILE FROM LOCAL MACHINE
export const UPLOAD_FILE_INITIATED = "UPLOAD_FILE_INITIATED";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";

// GET FILENAMES FROM S3
export const GET_LIST_INITIATED = "GET_LIST_INITIATED";
export const GET_LIST_FAILED = "GET_LIST_FAILED";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";

// LOAD FILE INFO
export const LOAD_INFO_INITIATED = "LOAD_INFO_INITIATED";
export const LOAD_INFO_FAILED = "LOAD_INFO_FAILED";
export const LOAD_INFO_SUCCESS = "LOAD_INFO_SUCCESS";

// GET BANK NAMES
export const GET_BANK_NAMES_INITIATED = "GET_BANK_NAMES_INITIATED";
export const GET_BANK_NAMES_FAILED = "GET_BANK_NAMES_FAILED";
export const GET_BANK_NAMES_SUCCESS = "GET_BANK_NAMES_SUCCESS";

// LOAD FILE FOR EXTRACTION
export const LOAD_FILE_INITIATED = "LOAD_FILE_INITIATED";
export const LOAD_FILE_FAILED = "LOAD_FILE_FAILED";
export const LOAD_FILE_SUCCESS = "LOAD_FILE_SUCCESS";
export const RETRIEVE_JSON_INITIATED = "RETRIEVE_JSON_INITIATED";
export const RETRIEVE_JSON_FAILED = "RETRIEVE_JSON_FAILED";
export const RETRIEVE_JSON_SUCCESS = "RETRIEVE_JSON_SUCCESS";
export const RESET_RETRIEVE_JSON_SUCCESS = "RESET_RETRIEVE_JSON_SUCCESS";

// SAVE JSON TO MONGO
export const SAVE_JSON_INITIATED = "SAVE_JSON_INITIATED";
export const SAVE_JSON_FAILED = "SAVE_JSON_FAILED";
export const SAVE_JSON_SUCCESS = "SAVE_JSON_SUCCESS";
export const RESET_SAVE_JSON_SUCCESS = "RESET_SAVE_JSON_SUCCESS";

// UPLOAD TEMPLATE
export const UPLOAD_TEMPLATE_INITIATED = "UPLOAD_TEMPLATE_INITIATED";
export const UPLOAD_TEMPLATE_SUCCESS = "UPLOAD_TEMPLATE_SUCCESS";
export const UPLOAD_TEMPLATE_FAILED = "UPLOAD_TEMPLATE_FAILED";

// EXTRACT DATA
export const EXTRACT_INITIATED = 'EXTRACT_INITIATED'
export const EXTRACT_SUCCESS = 'EXTRACT_SUCCESS'
export const EXTRACT_FAILED = 'EXTRACT_FAILED'

// SAVE TO POSTGRES
export const SAVE_TO_POSTGRES_INITIATED = 'SAVE_TO_POSTGRES_INITIATED'
export const SAVE_TO_POSTGRES_SUCCESS = 'SAVE_TO_POSTGRES_SUCCESS'
export const SAVE_TO_POSTGRES_FAILED = 'SAVE_TO_POSTGRES_FAILED'

// CHECK IF PROCESSED
export const CHECK_PROCESSED_INITIATED = 'CHECK_PROCESSED_INITIATED'
export const CHECK_PROCESSED_SUCCESS = 'CHECK_PROCESSED_SUCCESS'
export const CHECK_PROCESSED_FAILED = 'CHECK_PROCESSED_FAILED'